/*
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <https://unlicense.org>
 */
package matinilad.contentlist.ui.gui;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.filechooser.FileNameExtensionFilter;
import matinilad.contentlist.phantomfs.PhantomCreator;
import matinilad.contentlist.phantomfs.entry.FileEntry;
import matinilad.contentlist.phantomfs.entry.FileEntryCreator;
import matinilad.contentlist.phantomfs.entry.FileEntryWriter;

/**
 *
 * @author Cien
 */
@SuppressWarnings("serial")
public class NewCreateDialog extends javax.swing.JDialog {

    private static final Logger LOGGER = Logger.getLogger(NewCreateDialog.class.getName());
    
    /**
     * Creates new form NewCreateDialog
     */
    public NewCreateDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        outputFile = new javax.swing.JTextField();
        outputFileSelectButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputList = new javax.swing.JList<>();
        inputListAddButton = new javax.swing.JButton();
        inputListRemoveButton = new javax.swing.JButton();
        inputFilesClearButton = new javax.swing.JButton();
        inputListItemCount = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        metadataNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        metadataAuthorField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        metadataDescriptionArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New");
        setMinimumSize(new java.awt.Dimension(400, 340));

        createButton.setText("Create");
        createButton.setEnabled(false);
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Output File"));

        outputFile.setEditable(false);

        outputFileSelectButton.setText("...");
        outputFileSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFileSelectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputFileSelectButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputFileSelectButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Files (Drag and Drop Supported)"));

        inputList.setModel(new DefaultListModel<File>());
        this.inputList.addListSelectionListener(this::onListSelectionEvent);
        this.inputList.getModel().addListDataListener(new ListDataListener() {
            @Override
            public void intervalAdded(ListDataEvent e) {
                NewCreateDialog.this.onListDataChanged(e);
            }

            @Override
            public void intervalRemoved(ListDataEvent e) {
                NewCreateDialog.this.onListDataChanged(e);
            }

            @Override
            public void contentsChanged(ListDataEvent e) {

            }
        });
        jScrollPane2.setViewportView(inputList);
        this.inputList.setTransferHandler(new FileDragAndDrop() {
            @Override
            protected boolean process(List<File> files) {
                addFiles(files);
                return true;
            }
        });

        inputListAddButton.setText("Add");
        inputListAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputListAddButtonActionPerformed(evt);
            }
        });

        inputListRemoveButton.setText("Remove");
        inputListRemoveButton.setToolTipText("");
        inputListRemoveButton.setEnabled(false);
        inputListRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputListRemoveButtonActionPerformed(evt);
            }
        });

        inputFilesClearButton.setText("Clear");
        inputFilesClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFilesClearButtonActionPerformed(evt);
            }
        });

        inputListItemCount.setText("0 Items");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputListRemoveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputListAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputFilesClearButton)))
                    .addComponent(inputListItemCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(inputListAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputListRemoveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(inputFilesClearButton)))
                .addGap(9, 9, 9)
                .addComponent(inputListItemCount)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Files", jPanel1);

        jLabel2.setText("Name:");

        jLabel3.setText("Author:");

        metadataAuthorField.setText(System.getProperty("user.name"));

        jLabel4.setText("Description:");

        metadataDescriptionArea.setColumns(20);
        metadataDescriptionArea.setRows(5);
        jScrollPane3.setViewportView(metadataDescriptionArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(metadataNameField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(metadataAuthorField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metadataNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metadataAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Metadata", jPanel5);

        jMenu2.setText("Edit");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matinilad/contentlist/ui/gui/settings.png"))); // NOI18N
        jMenuItem1.setText("Settings");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createButton))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createButton)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Files");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFiles(List<File> files) {
        DefaultListModel<File> model = (DefaultListModel<File>) this.inputList.getModel();

        List<File> dir = new ArrayList<>();
        List<File> file = new ArrayList<>();

        for (File f : files) {
            if (model.contains(f)) {
                continue;
            }
            if (f.isDirectory()) {
                dir.add(f);
            } else {
                file.add(f);
            }
        }

        for (int i = 0; i < model.size(); i++) {
            File f = model.get(i);
            if (f.isDirectory()) {
                dir.add(f);
            } else {
                file.add(f);
            }
        }

        model.clear();

        Comparator<File> comparator = (o1, o2) -> {
            return String.CASE_INSENSITIVE_ORDER.compare(o1.getName(), o2.getName());
        };

        dir.sort(comparator);
        file.sort(comparator);

        model.addAll(dir);
        model.addAll(file);
    }

    private void outputFileSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFileSelectButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setFileFilter(new FileNameExtensionFilter("CSV Files (*.csv)", "csv"));
        chooser.setDialogType(JFileChooser.SAVE_DIALOG);
        if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();
        if (!file.getName().contains(".")) {
            file = new File(file.getParentFile(), file.getName() + ".csv");
        }

        this.outputFile.setText(file.toString());
        if (this.metadataNameField.getText().isEmpty()) {
            this.metadataNameField.setText(file.getName().split(Pattern.quote("."))[0]);
        }
        this.createButton.setEnabled(true);
    }//GEN-LAST:event_outputFileSelectButtonActionPerformed

    private void inputFilesClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFilesClearButtonActionPerformed
        ((DefaultListModel<File>) this.inputList.getModel()).clear();
    }//GEN-LAST:event_inputFilesClearButtonActionPerformed

    private void onListSelectionEvent(ListSelectionEvent e) {
        if (e.getValueIsAdjusting()) {
            return;
        }
        this.inputListRemoveButton.setEnabled(this.inputList.getSelectedIndices().length != 0);
    }

    private void inputListAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputListAddButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        addFiles(Arrays.asList(chooser.getSelectedFiles()));
    }//GEN-LAST:event_inputListAddButtonActionPerformed

    private void onListDataChanged(ListDataEvent e) {
        int count = this.inputList.getModel().getSize();
        this.inputListItemCount.setText(Integer.toString(count));
        if (count == 1) {
            this.inputListItemCount.setText(this.inputListItemCount.getText() + " Item");
        } else {
            this.inputListItemCount.setText(this.inputListItemCount.getText() + " Items");
        }
    }

    private void inputListRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputListRemoveButtonActionPerformed
        DefaultListModel<File> model = (DefaultListModel<File>) this.inputList.getModel();
        List<File> toRemove = this.inputList.getSelectedValuesList();
        for (File f : toRemove) {
            model.removeElement(f);
        }
    }//GEN-LAST:event_inputListRemoveButtonActionPerformed

    private void create(StatusDialog progressBar, File outputFile, List<File> inputFiles) throws IOException, InterruptedException {
        try (FileEntryWriter writer = new FileEntryWriter(new OutputStreamWriter(new BufferedOutputStream(new FileOutputStream(outputFile)), StandardCharsets.UTF_8), 0)) {
            AtomicInteger entriesWritten = new AtomicInteger();
            PhantomCreator creator = new PhantomCreator() {
                @Override
                protected void onShouldFileBeRejected(Path file) throws IOException, InterruptedException {
                    if (file.toFile().equals(outputFile)) {
                        throw new IOException("output file must not be used as input file!");
                    }
                }
                
                @Override
                protected void onFileRejected(Path file, IOException reason) throws IOException, InterruptedException {
                    LOGGER.log(Level.WARNING, "error on "+file.toString(), reason);
                }
                
                @Override
                protected void onEntry(FileEntry entry) throws IOException, InterruptedException {
                    writer.writeFileEntry(entry);
                    LOGGER.log(Level.INFO, "written {0}", entry.getPath().toString());
                    entriesWritten.incrementAndGet();
                    SwingUtilities.invokeLater(() -> {
                        progressBar.getCurrentGlobalStatus().setText(entriesWritten.get()+" Entries");
                    });
                }
            };
            FileEntryCreator fileEntryCreator = new FileEntryCreator() {
                @Override
                protected void onEntryCreated(FileEntry entry) throws IOException, InterruptedException {
                    LOGGER.log(Level.INFO, "created {0}", entry.getPath().toString());
                    SwingUtilities.invokeLater(() -> {
                        progressBar.updateAndResetTime(entry.getPath().toString());
                    });
                }
                
                @Override
                protected void onEntryProgress(FileEntry entry, long bytes) throws IOException, InterruptedException {
                    if (entry.getSize() != 0) {
                        SwingUtilities.invokeLater(() -> {
                            progressBar.setCurrentProgress((float) (bytes / ((double)entry.getSize())));
                        });
                    }
                }
            };
            creator.setFileEntryCreator(fileEntryCreator);
            
            creator.create(inputFiles.stream().map(File::toPath).toArray(Path[]::new));
        }
    }
    
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        File output = new File(this.outputFile.getText());
        if (output.exists()) {
            Toolkit.getDefaultToolkit().beep();
            if (output.isDirectory()) {
                JOptionPane.showMessageDialog(this,
                        "'"+output.toString()+"' is a directory, cannot continue!",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int result = JOptionPane.showConfirmDialog(this,
                    "'"+output.toString()+"' already exists, overwrite file?",
                    "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (result != JOptionPane.YES_OPTION) {
                return;
            }
        }
        List<File> inputFiles = new ArrayList<>();
        for (int i = 0; i < this.inputList.getModel().getSize(); i++) {
            inputFiles.add(this.inputList.getModel().getElementAt(i));
        }
        
        StatusDialog dialog = new StatusDialog(this, true);
        dialog.setTitle(output.toString());
        LOGGER.addHandler(dialog.getLoggerHandler());
        
        Thread th = new Thread(() -> {
            try {
                create(dialog, output, inputFiles);
            } catch (InterruptedException e) {
                LOGGER.log(Level.INFO, "interrupted by user", e);
                if (!output.delete()) {
                    LOGGER.log(Level.SEVERE, "could not delete {0}", output);
                }
            } catch (Throwable t) {
                LOGGER.log(Level.SEVERE, null, t);
            }
            SwingUtilities.invokeLater(() -> {
                LOGGER.info("finished!");
                LOGGER.removeHandler(dialog.getLoggerHandler());
                dialog.getCancelButton().setEnabled(false);
                dialog.updateAndResetTime("Finished!");
                Toolkit.getDefaultToolkit().beep();
            });
        }, "create-content-list");
        dialog.getCancelButton().addActionListener((e) -> {
            th.interrupt();
        });
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                NewCreateDialog.this.setVisible(false);
                NewCreateDialog.this.dispose();
            }
        });
        th.setDaemon(true);
        th.start();
        
        dialog.setVisible(true);
    }//GEN-LAST:event_createButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JButton inputFilesClearButton;
    private javax.swing.JList<File> inputList;
    private javax.swing.JButton inputListAddButton;
    private javax.swing.JLabel inputListItemCount;
    private javax.swing.JButton inputListRemoveButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField metadataAuthorField;
    private javax.swing.JTextArea metadataDescriptionArea;
    private javax.swing.JTextField metadataNameField;
    private javax.swing.JTextField outputFile;
    private javax.swing.JButton outputFileSelectButton;
    // End of variables declaration//GEN-END:variables
}
