/*
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <https://unlicense.org>
 */
package matinilad.contentlist.ui.gui;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedOutputStream;
import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import java.util.zip.GZIPOutputStream;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.SwingUtilities;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.filechooser.FileNameExtensionFilter;
import matinilad.contentlist.phantomfs.PhantomFileSystem;
import matinilad.contentlist.phantomfs.PhantomPath;
import matinilad.contentlist.phantomfs.entry.FileEntry;
import matinilad.contentlist.phantomfs.entry.FileEntryFactory;
import matinilad.contentlist.phantomfs.entry.FileEntryMetadata;
import matinilad.contentlist.phantomfs.entry.FileEntryType;
import matinilad.contentlist.phantomfs.entry.FileEntryWriter;
import matinilad.contentlist.phantomfs.utils.EncryptedOutputStream;
import matinilad.contentlist.phantomfs.utils.PathStream;
import matinilad.contentlist.phantomfs.utils.TempFileList;
import matinilad.contentlist.ui.UIUtils;

/**
 *
 * @author Cien
 */
@SuppressWarnings("serial")
public class NewDialog extends javax.swing.JDialog {

    private static final Logger LOGGER = Logger.getLogger(NewDialog.class.getName());

    /**
     * Creates new form NewCreateDialog
     */
    public NewDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        outputFile = new javax.swing.JTextField();
        outputFileSelectButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputList = new javax.swing.JList<>();
        inputListAddButton = new javax.swing.JButton();
        inputListRemoveButton = new javax.swing.JButton();
        inputFilesClearButton = new javax.swing.JButton();
        inputListItemCount = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        metadataNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        metadataAuthorField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        metadataDescriptionArea = new javax.swing.JTextArea();
        setUsernameToAuthorButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        noFilesAndDirectoriesButton = new javax.swing.JCheckBox();
        noSha256Button = new javax.swing.JCheckBox();
        noFileSampleButton = new javax.swing.JCheckBox();
        noMetadataButton = new javax.swing.JCheckBox();
        fileSampleSizeSpinner = new javax.swing.JSpinner();
        fileSampleSizeLabel = new javax.swing.JLabel();
        noFileTypeButton = new javax.swing.JCheckBox();
        noTimestampsButton = new javax.swing.JCheckBox();
        noFileSizeButton = new javax.swing.JCheckBox();
        includeHiddenFilesCheckbox = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        encryptWithAPasswordCheckbox = new javax.swing.JCheckBox();
        passwordField = new javax.swing.JPasswordField();
        saltLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        saltArea = new javax.swing.JTextArea();
        confirmPasswordField = new javax.swing.JPasswordField();
        confirmPasswordLabel = new javax.swing.JLabel();
        showPasswordCheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New");
        setMinimumSize(new java.awt.Dimension(400, 340));

        createButton.setText("Create");
        createButton.setEnabled(false);
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Output File"));

        outputFile.setEditable(false);

        outputFileSelectButton.setText("...");
        outputFileSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFileSelectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputFileSelectButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputFileSelectButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Files (Drag and Drop Supported)"));

        inputList.setModel(new DefaultListModel<File>());
        this.inputList.addListSelectionListener(this::onListSelectionEvent);
        this.inputList.getModel().addListDataListener(new ListDataListener() {
            @Override
            public void intervalAdded(ListDataEvent e) {
                NewDialog.this.onListDataChanged(e);
            }

            @Override
            public void intervalRemoved(ListDataEvent e) {
                NewDialog.this.onListDataChanged(e);
            }

            @Override
            public void contentsChanged(ListDataEvent e) {

            }
        });
        jScrollPane2.setViewportView(inputList);
        this.inputList.setTransferHandler(new FileDragAndDrop() {
            @Override
            protected boolean process(List<File> files) {
                addFiles(files);
                return true;
            }
        });

        inputListAddButton.setText("Add");
        inputListAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputListAddButtonActionPerformed(evt);
            }
        });

        inputListRemoveButton.setText("Remove");
        inputListRemoveButton.setToolTipText("");
        inputListRemoveButton.setEnabled(false);
        inputListRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputListRemoveButtonActionPerformed(evt);
            }
        });

        inputFilesClearButton.setText("Clear");
        inputFilesClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFilesClearButtonActionPerformed(evt);
            }
        });

        inputListItemCount.setText("0 Items");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputListRemoveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputListAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputFilesClearButton)))
                    .addComponent(inputListItemCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(inputListAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputListRemoveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(inputFilesClearButton)))
                .addGap(9, 9, 9)
                .addComponent(inputListItemCount)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Files", jPanel1);

        jLabel2.setText("Name:");

        jLabel3.setText("Author:");

        jLabel4.setText("Description:");

        metadataDescriptionArea.setColumns(20);
        metadataDescriptionArea.setRows(5);
        jScrollPane3.setViewportView(metadataDescriptionArea);

        setUsernameToAuthorButton.setText("Username");
        setUsernameToAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setUsernameToAuthorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addComponent(metadataNameField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(metadataAuthorField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setUsernameToAuthorButton)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metadataNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(metadataAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setUsernameToAuthorButton))
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Info", jPanel5);

        noFilesAndDirectoriesButton.setText("Don't write files and directories count");

        noSha256Button.setText("Don't write file SHA256");

        noFileSampleButton.setText("Don't write file sample");
        noFileSampleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noFileSampleButtonActionPerformed(evt);
            }
        });

        noMetadataButton.setText("Don't write metadata");

        fileSampleSizeSpinner.setModel(new javax.swing.SpinnerNumberModel(32, 0, 64, 1));

        fileSampleSizeLabel.setText("File sample size (in bytes):");

        noFileTypeButton.setText("Don't write file type");

        noTimestampsButton.setText("Don't write timestamps");

        noFileSizeButton.setText("Don't write file size");

        includeHiddenFilesCheckbox.setText("Include hidden files");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noSha256Button, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noTimestampsButton)
                            .addComponent(noMetadataButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noFileTypeButton)
                            .addComponent(noFileSampleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noFileSizeButton)
                            .addComponent(noFilesAndDirectoriesButton)
                            .addComponent(fileSampleSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fileSampleSizeLabel)
                            .addComponent(includeHiddenFilesCheckbox))
                        .addGap(0, 165, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noFileTypeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTimestampsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noFileSizeButton)
                .addGap(6, 6, 6)
                .addComponent(noFilesAndDirectoriesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noSha256Button)
                .addGap(6, 6, 6)
                .addComponent(noFileSampleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noMetadataButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileSampleSizeLabel)
                .addGap(6, 6, 6)
                .addComponent(fileSampleSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(includeHiddenFilesCheckbox)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Settings", jPanel2);

        encryptWithAPasswordCheckbox.setText("Encrypt with a password:");
        encryptWithAPasswordCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptWithAPasswordCheckboxActionPerformed(evt);
            }
        });

        passwordField.setEnabled(false);

        saltLabel.setText("Salt (type random characters below or leave empty to skip):");
        saltLabel.setEnabled(false);

        saltArea.setColumns(20);
        saltArea.setRows(5);
        saltArea.setEnabled(false);
        jScrollPane1.setViewportView(saltArea);

        confirmPasswordField.setEnabled(false);

        confirmPasswordLabel.setText("Confirm password:");
        confirmPasswordLabel.setEnabled(false);

        showPasswordCheckbox.setText("Show");
        showPasswordCheckbox.setEnabled(false);
        showPasswordCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmPasswordField)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(encryptWithAPasswordCheckbox)
                            .addComponent(saltLabel)
                            .addComponent(confirmPasswordLabel))
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(passwordField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showPasswordCheckbox)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(encryptWithAPasswordCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPasswordCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saltLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Encrypt", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createButton))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createButton)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Files");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFiles(List<File> files) {
        DefaultListModel<File> model = (DefaultListModel<File>) this.inputList.getModel();

        List<File> dir = new ArrayList<>();
        List<File> file = new ArrayList<>();

        for (File f : files) {
            if (model.contains(f)) {
                continue;
            }
            if (f.isDirectory()) {
                dir.add(f);
            } else {
                file.add(f);
            }
        }

        for (int i = 0; i < model.size(); i++) {
            File f = model.get(i);
            if (f.isDirectory()) {
                dir.add(f);
            } else {
                file.add(f);
            }
        }

        model.clear();

        Comparator<File> comparator = (o1, o2) -> {
            return String.CASE_INSENSITIVE_ORDER.compare(o1.getName(), o2.getName());
        };

        dir.sort(comparator);
        file.sort(comparator);

        model.addAll(dir);
        model.addAll(file);
    }

    private void outputFileSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFileSelectButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (this.encryptWithAPasswordCheckbox.isSelected()) {
            chooser.setFileFilter(new FileNameExtensionFilter("BIN Files (*.bin)", "bin"));
        } else {
            chooser.setFileFilter(new FileNameExtensionFilter("CSV Files (*.csv)", "csv"));
        }
        chooser.setDialogType(JFileChooser.SAVE_DIALOG);
        if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();
        if (!file.getName().contains(".")) {
            if (this.encryptWithAPasswordCheckbox.isSelected()) {
                file = new File(file.getParentFile(), file.getName() + ".bin");
            } else {
                file = new File(file.getParentFile(), file.getName() + ".csv");
            }
        }

        this.outputFile.setText(file.toString());
        if (this.metadataNameField.getText().isEmpty()) {
            this.metadataNameField.setText(file.getName().split(Pattern.quote("."))[0]);
        }
        this.createButton.setEnabled(true);
    }//GEN-LAST:event_outputFileSelectButtonActionPerformed

    private void inputFilesClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFilesClearButtonActionPerformed
        ((DefaultListModel<File>) this.inputList.getModel()).clear();
    }//GEN-LAST:event_inputFilesClearButtonActionPerformed

    private void onListSelectionEvent(ListSelectionEvent e) {
        if (e.getValueIsAdjusting()) {
            return;
        }
        this.inputListRemoveButton.setEnabled(this.inputList.getSelectedIndices().length != 0);
    }

    private void inputListAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputListAddButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }

        addFiles(Arrays.asList(chooser.getSelectedFiles()));
    }//GEN-LAST:event_inputListAddButtonActionPerformed

    private void onListDataChanged(ListDataEvent e) {
        int count = this.inputList.getModel().getSize();
        this.inputListItemCount.setText(Integer.toString(count));
        if (count == 1) {
            this.inputListItemCount.setText(this.inputListItemCount.getText() + " Item");
        } else {
            this.inputListItemCount.setText(this.inputListItemCount.getText() + " Items");
        }
    }

    private void inputListRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputListRemoveButtonActionPerformed
        DefaultListModel<File> model = (DefaultListModel<File>) this.inputList.getModel();
        List<File> toRemove = this.inputList.getSelectedValuesList();
        for (File f : toRemove) {
            model.removeElement(f);
        }
    }//GEN-LAST:event_inputListRemoveButtonActionPerformed

    private void create(
            StatusDialog progressBar,
            File outputFile,
            List<File> inputFiles,
            FileEntryWriter.Flags flags, int sampleSize,
            String name, String author, String description,
            byte[] userSalt, char[] password,
            boolean includeHiddenFiles
    ) throws IOException, InterruptedException {
        LOGGER.log(Level.INFO, "Creating list on {0} for {1}",
                new Object[]{
                    outputFile.toString(),
                    inputFiles.stream().map(File::toString).collect(Collectors.joining(File.pathSeparator))
                });
        StatusDialogFileItem fileStatus = new StatusDialogFileItem(progressBar);
        fileStatus.reset();
        fileStatus.updateDialog(true);

        TempFileList tempFile = new TempFileList();
        try {
            OutputStream out = tempFile.newOutputStream(outputFile.toPath());
            if (password != null) {
                out = new GZIPOutputStream(new EncryptedOutputStream(out, userSalt, password));
            }
            
            try (FileEntryWriter w = new FileEntryWriter(new BufferedWriter(new OutputStreamWriter(out, StandardCharsets.UTF_8)), flags)) {
                PhantomFileSystem fs = new PhantomFileSystem();

                FileEntryFactory factory = new FileEntryFactory() {
                    @Override
                    protected void onFileProgress(Path path, long currentCount, long totalBytes) {
                        if (totalBytes != 0) {
                            if (fileStatus.getFileSize() == 0) {
                                fileStatus.setFileSize(totalBytes);
                            }
                            fileStatus.setFileProgress(currentCount);
                            fileStatus.updateDialog(false);
                        }
                    }
                };
                factory.setSampleSize(sampleSize);
                factory.setSha256Enabled(flags.isSha256Enabled());

                AtomicInteger entries = new AtomicInteger(0);
                AtomicLong totalSize = new AtomicLong(0);

                Path[] input = new Path[inputFiles.size()];
                for (int i = 0; i < input.length; i++) {
                    input[i] = inputFiles.get(i).toPath();
                }
                PathStream stream = new PathStream(input, includeHiddenFiles);
                try {
                    stream.stream((e) -> {
                        Path file = e.getPath();
                        try {
                            if (e.getError() != null) {
                                throw e.getError();
                            }

                            LOGGER.log(Level.INFO, "Reading {0}", file.toString());

                            fileStatus.reset();
                            fileStatus.setFileName(file.toString());
                            fileStatus.updateDialog(false);

                            FileEntry entry = factory.newFileEntry(e.getRoot(), file);
                            fs.writeEntry(entry);

                            if (entry.getType().equals(FileEntryType.FILE)) {
                                totalSize.addAndGet(entry.getSize());
                            }

                            progressBar.updateCurrentGlobalStatusAsync(
                                    entries.incrementAndGet() + " Entries with " + UIUtils.formatBytesShort(totalSize.get()) + " in total",
                                    false
                            );
                        } catch (Throwable t) {
                            if (t instanceof InterruptedException ex) {
                                throw new RuntimeException(ex);
                            } else {
                                LOGGER.log(Level.WARNING, "Error on " + file.toString(), e.getError());
                            }
                        }
                    });
                } catch (RuntimeException ex) {
                    if (ex.getCause() instanceof InterruptedException in) {
                        throw in;
                    }
                    throw ex;
                }

                fs.validate();

                FileEntry rootEntry = fs.getEntry(PhantomPath.of("/"));
                FileEntryMetadata meta = rootEntry.getMetadata();
                if (name != null) {
                    meta.writeString(FileEntry.METADATA_NAME, name);
                }
                if (author != null) {
                    meta.writeString(FileEntry.METADATA_AUTHOR, author);
                }
                if (description != null) {
                    meta.writeString(FileEntry.METADATA_DESCRIPTION, description);
                }

                if (Thread.interrupted()) {
                    throw new InterruptedException();
                }
                for (FileEntry e : fs.listEntries()) {
                    if (Thread.interrupted()) {
                        throw new InterruptedException();
                    }
                    w.writeFileEntry(e);
                }

                progressBar.updateCurrentGlobalStatusAsync(
                        entries.get() + " Entries with " + UIUtils.formatBytesShort(totalSize.get()) + " in total",
                        true
                );
            }
            
        } catch (Throwable t) {
            tempFile.deleteFiles();
            throw t;
        }
    }

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        File output = new File(this.outputFile.getText());
        if (output.exists()) {
            Toolkit.getDefaultToolkit().beep();
            if (output.isDirectory()) {
                JOptionPane.showMessageDialog(this,
                        "'" + output.toString() + "' is a directory, cannot continue!",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int result = JOptionPane.showConfirmDialog(this,
                    "'" + output.toString() + "' already exists, overwrite file?",
                    "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (result != JOptionPane.YES_OPTION) {
                return;
            }
        }

        FileEntryWriter.Flags flags = new FileEntryWriter.Flags();

        if (this.noFileTypeButton.isSelected()) {
            flags.setTypeEnabled(false);
        }
        if (this.noTimestampsButton.isSelected()) {
            flags.setTimestampsEnabled(false);
        }
        if (this.noFileSizeButton.isSelected()) {
            flags.setSizeEnabled(false);
        }
        if (this.noFilesAndDirectoriesButton.isSelected()) {
            flags.setFilesAndDirectoriesEnabled(false);
        }
        if (this.noSha256Button.isSelected()) {
            flags.setSha256Enabled(false);
        }
        if (this.noFileSampleButton.isSelected()) {
            flags.setSampleEnabled(false);
        }
        if (this.noMetadataButton.isSelected()) {
            flags.setMetadataEnabled(false);
        }

        int sampleSize = (int) this.fileSampleSizeSpinner.getValue();
        if (sampleSize == 0) {
            flags.setSampleEnabled(false);
        } else if (!flags.isSampleEnabled()) {
            sampleSize = 0;
        }

        List<File> inputFiles = new ArrayList<>();
        for (int i = 0; i < this.inputList.getModel().getSize(); i++) {
            inputFiles.add(this.inputList.getModel().getElementAt(i));
        }

        int finalSampleSize = sampleSize;
        String name = this.metadataNameField.getText();
        String author = this.metadataAuthorField.getText();
        String description = this.metadataDescriptionArea.getText();

        byte[] userSalt = null;
        char[] password = null;

        if (this.encryptWithAPasswordCheckbox.isSelected()) {
            password = this.passwordField.getPassword();
            if (password.length == 0) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Password is empty", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!this.showPasswordCheckbox.isSelected()) {
                char[] confirmPassword = this.confirmPasswordField.getPassword();
                if (!Arrays.equals(password, confirmPassword)) {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "Passwords are not equal", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if (!this.saltArea.getText().isEmpty()) {
                userSalt = this.saltArea.getText().getBytes(StandardCharsets.UTF_8);
            }
            this.passwordField.setText("");
            this.confirmPasswordField.setText("");
        }

        final boolean includeHiddenFiles = this.includeHiddenFilesCheckbox.isSelected();
        final byte[] finalUserSalt = userSalt;
        final char[] finalPassword = password;

        StatusDialog dialog = new StatusDialog(this, true);
        dialog.setTitle(output.toString());
        LOGGER.addHandler(dialog.getLoggerHandler());

        AtomicBoolean canceled = new AtomicBoolean(false);
        Thread th = new Thread(() -> {
            try {
                create(dialog, output, inputFiles, flags, finalSampleSize, name, author, description, finalUserSalt, finalPassword, includeHiddenFiles);
            } catch (InterruptedException e) {
                LOGGER.log(Level.INFO, "Interrupted by user", e);
            } catch (Throwable t) {
                LOGGER.log(Level.SEVERE, null, t);
            } finally {
                if (finalPassword != null) {
                    Arrays.fill(finalPassword, '\0');
                }
            }
            SwingUtilities.invokeLater(() -> {
                LOGGER.info("Finished!");
                LOGGER.removeHandler(dialog.getLoggerHandler());
                dialog.getCancelButton().setEnabled(false);
                dialog.getCurrentItemName().setText("Finished");
                dialog.getCurrentItemStatus().setText("");
                dialog.setProgress(0f);
                Toolkit.getDefaultToolkit().beep();
            });
        });
        dialog.getCancelButton().addActionListener((e) -> {
            if (dialog.showCancelDialog()) {
                th.interrupt();
                dialog.setVisible(false);
                dialog.dispose();
                canceled.set(true);
            }
        });
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                if (!canceled.get()) {
                    NewDialog.this.setVisible(false);
                    NewDialog.this.dispose();
                }
            }
        });
        th.setDaemon(true);
        th.start();

        dialog.setVisible(true);
    }//GEN-LAST:event_createButtonActionPerformed

    private void setUsernameToAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setUsernameToAuthorButtonActionPerformed
        this.metadataAuthorField.setText(System.getProperty("user.name"));
    }//GEN-LAST:event_setUsernameToAuthorButtonActionPerformed

    private void noFileSampleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noFileSampleButtonActionPerformed
        boolean value = this.noFileSampleButton.isSelected();
        this.fileSampleSizeLabel.setEnabled(!value);
        this.fileSampleSizeSpinner.setEnabled(!value);
    }//GEN-LAST:event_noFileSampleButtonActionPerformed

    private String mirror(String s) {
        StringBuilder b = new StringBuilder();
        for (int i = s.length() - 1; i >= 0; i--) {
            b.append(s.charAt(i));
        }
        return b.toString();
    }

    private void encryptWithAPasswordCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptWithAPasswordCheckboxActionPerformed
        boolean b = this.encryptWithAPasswordCheckbox.isSelected();
        this.passwordField.setText("");
        this.confirmPasswordField.setText("");
        this.showPasswordCheckbox.setSelected(false);
        this.passwordField.setEnabled(b);
        this.showPasswordCheckbox.setEnabled(b);
        this.confirmPasswordLabel.setEnabled(b);
        this.confirmPasswordField.setEnabled(b);
        this.saltLabel.setEnabled(b);
        this.saltArea.setEnabled(b);

        if (!this.outputFile.getText().isEmpty()) {
            String[] split = mirror(this.outputFile.getText()).split("\\.", 2);
            if (split.length == 2) {
                String ext = mirror(split[0]).toLowerCase();
                String name = mirror(split[1]);
                if (ext.equals("bin") || ext.equals("csv")) {
                    if (b) {
                        this.outputFile.setText(name + ".bin");
                    } else {
                        this.outputFile.setText(name + ".csv");
                    }
                }
            }
        }
    }//GEN-LAST:event_encryptWithAPasswordCheckboxActionPerformed

    private void showPasswordCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckboxActionPerformed
        boolean b = this.showPasswordCheckbox.isSelected();
        if (b) {
            this.passwordField.setEchoChar('\0');
        } else {
            this.passwordField.setEchoChar(new JPasswordField().getEchoChar());
        }
        this.confirmPasswordField.setEnabled(!b);
        this.confirmPasswordLabel.setEnabled(!b);
    }//GEN-LAST:event_showPasswordCheckboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JCheckBox encryptWithAPasswordCheckbox;
    private javax.swing.JLabel fileSampleSizeLabel;
    private javax.swing.JSpinner fileSampleSizeSpinner;
    private javax.swing.JCheckBox includeHiddenFilesCheckbox;
    private javax.swing.JButton inputFilesClearButton;
    private javax.swing.JList<File> inputList;
    private javax.swing.JButton inputListAddButton;
    private javax.swing.JLabel inputListItemCount;
    private javax.swing.JButton inputListRemoveButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField metadataAuthorField;
    private javax.swing.JTextArea metadataDescriptionArea;
    private javax.swing.JTextField metadataNameField;
    private javax.swing.JCheckBox noFileSampleButton;
    private javax.swing.JCheckBox noFileSizeButton;
    private javax.swing.JCheckBox noFileTypeButton;
    private javax.swing.JCheckBox noFilesAndDirectoriesButton;
    private javax.swing.JCheckBox noMetadataButton;
    private javax.swing.JCheckBox noSha256Button;
    private javax.swing.JCheckBox noTimestampsButton;
    private javax.swing.JTextField outputFile;
    private javax.swing.JButton outputFileSelectButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextArea saltArea;
    private javax.swing.JLabel saltLabel;
    private javax.swing.JButton setUsernameToAuthorButton;
    private javax.swing.JCheckBox showPasswordCheckbox;
    // End of variables declaration//GEN-END:variables
}
