/*
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <https://unlicense.org>
 */
package matinilad.contentlist.ui.gui;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.logging.ErrorManager;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.LogRecord;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JButton;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Cien
 */
@SuppressWarnings("serial")
public class StatusDialog extends javax.swing.JDialog {

    private static final Logger LOGGER = Logger.getLogger(StatusDialog.class.getName());

    private final Handler loggerHandler = new Handler() {
        private int warnings = 0;
        private int errors = 0;

        {
            setFormatter(new SimpleFormatter());
        }

        @Override
        public synchronized void setLevel(Level newLevel) throws SecurityException {
            super.setLevel(newLevel);
            
            //todo: menu bar logic
        }
        
        @Override
        public void publish(LogRecord record) {
            if (!isLoggable(record)) {
                return;
            }
            String msg;
            try {
                msg = getFormatter().format(record);
            } catch (Exception ex) {
                reportError(null, ex, ErrorManager.FORMAT_FAILURE);
                return;
            }

            int recordLevel = record.getLevel().intValue();
            boolean updatedCount = false;
            if (recordLevel >= Level.WARNING.intValue() && recordLevel < Level.SEVERE.intValue()) {
                updatedCount = true;
                this.warnings++;
            }
            if (recordLevel >= Level.SEVERE.intValue()) {
                updatedCount = true;
                this.errors++;
            }

            final boolean finalUpdatedCount = updatedCount;
            SwingUtilities.invokeLater(() -> {
                StatusDialog.this.logTextArea.append(msg);
                if (finalUpdatedCount) {
                    StringBuilder b = new StringBuilder();
                    b.append(this.warnings);
                    if (this.warnings == 1) {
                        b.append(" Warning, ");
                    } else {
                        b.append(" Warnings, ");
                    }
                    b.append(this.errors);
                    if (this.errors == 1) {
                        b.append(" Error");
                    } else {
                        b.append(" Errors");
                    }
                    StatusDialog.this.logCount.setText(b.toString());
                }
            });
        }

        @Override
        public void flush() {

        }

        @Override
        public void close() throws SecurityException {

        }
    };

    private long progressTime = System.nanoTime();
    private float currentProgress = 0f;

    public StatusDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public StatusDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        statusPanel = new javax.swing.JPanel();
        currentItemName = new javax.swing.JTextField();
        progressBar = new javax.swing.JProgressBar();
        progressLabel = new javax.swing.JLabel();
        estimatedTime = new javax.swing.JLabel();
        currentItemStatus = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        currentGlobalStatus = new javax.swing.JTextField();
        logCount = new javax.swing.JLabel();
        logPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        saveLogButton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        logLevelMenu = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        clearLogButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Title");
        setMinimumSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        currentItemName.setEditable(false);
        currentItemName.setText("Current Item Name");
        currentItemName.setBorder(null);

        progressBar.setMaximum(100000);
        progressBar.setValue(50000);

        progressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progressLabel.setText("50%");

        estimatedTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estimatedTime.setText("10d 10h 10m 10s estimated");

        currentItemStatus.setEditable(false);
        currentItemStatus.setText("Current Item Status");
        currentItemStatus.setBorder(null);

        cancelButton.setText("Cancel");

        currentGlobalStatus.setEditable(false);
        currentGlobalStatus.setText("Current Global Status");
        currentGlobalStatus.setBorder(null);

        logCount.setText("0 Warnings, 0 Errors");

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(currentGlobalStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(currentItemStatus)
                    .addComponent(logCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estimatedTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentItemName)
                    .addComponent(progressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(currentItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estimatedTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentItemStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(currentGlobalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Status", statusPanel);

        logTextArea.setEditable(false);
        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        jScrollPane1.setViewportView(logTextArea);

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Details", logPanel);

        jMenu1.setText("File");

        saveLogButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveLogButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matinilad/contentlist/ui/gui/save.png"))); // NOI18N
        saveLogButton.setText("Save Log");
        saveLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveLogButtonActionPerformed(evt);
            }
        });
        jMenu1.add(saveLogButton);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        logLevelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matinilad/contentlist/ui/gui/log.png"))); // NOI18N
        logLevelMenu.setText("Log Level");
        {
            Level[] levels = {Level.ALL, Level.INFO, Level.WARNING, Level.SEVERE, Level.OFF};
            this.loggerHandler.setLevel(Level.WARNING);
            for (int i = 0; i < levels.length; i++) {
                Level level = levels[i];
                if (level.equals(Level.INFO) || level.equals(Level.OFF)) {
                    this.logLevelMenu.add(new JSeparator());
                }
                JCheckBoxMenuItem item = new JCheckBoxMenuItem(level.getLocalizedName());
                item.setSelected(level.equals(Level.WARNING));
                item.addActionListener((evt) -> {
                    for (int j = 0; j < this.logLevelMenu.getItemCount(); j++) {
                        if (this.logLevelMenu.getItem(j) instanceof JCheckBoxMenuItem e) {
                            e.setSelected(false);
                        }
                    }
                    item.setSelected(true);
                    this.loggerHandler.setLevel(level);
                });
                this.logLevelMenu.add(item);
            }
        }
        jMenu2.add(logLevelMenu);
        jMenu2.add(jSeparator1);

        clearLogButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        clearLogButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matinilad/contentlist/ui/gui/clear.png"))); // NOI18N
        clearLogButton.setText("Clear Log");
        clearLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLogButtonActionPerformed(evt);
            }
        });
        jMenu2.add(clearLogButton);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        getCancelButton().doClick();
    }//GEN-LAST:event_formWindowClosing

    private void clearLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLogButtonActionPerformed
        int result = JOptionPane
                .showConfirmDialog(
                        this, "Clear Log?", "Confirm Action",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result != JOptionPane.YES_OPTION) {
            return;
        }
        this.logTextArea.setText("");
        Toolkit.getDefaultToolkit().beep();
    }//GEN-LAST:event_clearLogButtonActionPerformed

    private void saveLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLogButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogType(JFileChooser.SAVE_DIALOG);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter logFile = new FileNameExtensionFilter("Log File (.log)", "log");
        FileNameExtensionFilter textFile = new FileNameExtensionFilter("Text File (.txt)", "txt");
        chooser.addChoosableFileFilter(logFile);
        chooser.addChoosableFileFilter(textFile);
        chooser.setFileFilter(logFile);
        chooser.setMultiSelectionEnabled(false);
        int result = chooser.showSaveDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File selected = chooser.getSelectedFile();
        if (!selected.getName().contains(".")) {
            String extension = ".log";
            if (chooser.getFileFilter() instanceof FileNameExtensionFilter e) {
                String[] extensions = e.getExtensions();
                if (extensions != null && extensions.length > 0) {
                    extension = "." + extensions[0];
                }
            }
            selected = new File(selected.getParentFile(), selected.getName() + extension);
        }
        try {
            try (FileOutputStream o = new FileOutputStream(selected)) {
                o.write(this.logTextArea.getText().getBytes(StandardCharsets.UTF_8));
            }
            LOGGER.log(Level.INFO, "Log saved to: {0}", selected.toString());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Failed to save file! Check log for details", "Failed!", JOptionPane.ERROR_MESSAGE);
            LOGGER.log(Level.WARNING, "Failed to save log to: " + selected.toString(), ex);
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_saveLogButtonActionPerformed

    public Handler getLoggerHandler() {
        return loggerHandler;
    }

    public JTextField getCurrentItemName() {
        return currentItemName;
    }

    public JTextField getCurrentItemStatus() {
        return currentItemStatus;
    }

    public JTextField getCurrentGlobalStatus() {
        return currentGlobalStatus;
    }

    public long getProgressTime() {
        return progressTime;
    }

    public void resetProgressTime() {
        this.progressTime = System.nanoTime();
    }

    public void setCurrentProgress(float progress) {
        progress = Math.min(Math.max(progress, 0f), 1f);
        this.currentProgress = progress;

        this.progressBar.setValue((int) (progress * this.progressBar.getMaximum()));
        this.progressLabel.setText(String.format("%.2f%%", progress * 100f));

        if (progress < 0.00001f) {
            this.estimatedTime.setText("waiting");
        } else {
            int seconds = (int) ((((System.nanoTime() - getProgressTime()) / 1E9d) / progress) * (1f - progress));
            int hours = seconds / 3600;
            seconds -= hours * 3600;
            int minutes = seconds / 60;
            seconds -= minutes * 60;

            StringBuilder b = new StringBuilder();
            if (hours != 0) {
                b.append(hours).append("h ");
            }
            if (minutes != 0) {
                b.append(minutes).append("m ");
            }
            b.append(seconds).append("s remaining");

            this.estimatedTime.setText(b.toString());
        }
    }

    public float getCurrentProgress() {
        return currentProgress;
    }

    public void updateAndResetTime(String itemName) {
        getCurrentItemName().setText(itemName);
        getCurrentItemStatus().setText("");
        resetProgressTime();
        setCurrentProgress(0f);
    }

    public JButton getCancelButton() {
        return cancelButton;
    }

    public void removeStatusPanel() {
        for (int i = 0; i < this.jTabbedPane1.getTabCount(); i++) {
            if (this.jTabbedPane1.getComponentAt(i) == this.statusPanel) {
                this.jTabbedPane1.removeTabAt(i);
                break;
            }
        }
    }
    
    @Deprecated
    public void println(String line) {
        this.logTextArea.append(line + "\n");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JMenuItem clearLogButton;
    private javax.swing.JTextField currentGlobalStatus;
    private javax.swing.JTextField currentItemName;
    private javax.swing.JTextField currentItemStatus;
    private javax.swing.JLabel estimatedTime;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logCount;
    private javax.swing.JMenu logLevelMenu;
    private javax.swing.JPanel logPanel;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JMenuItem saveLogButton;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables
}
